apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark-job
spec:
  template:
    spec:
      containers:
      - name: benchmark
        image: cdle-benchmarking
        command: ["/bin/bash", "-c"]
        args:
          - |
            export PYENV_ROOT="/root/.pyenv" &&
            export PATH="$PYENV_ROOT/bin:$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH" &&
            eval "$(pyenv init --path)" &&
            eval "$(pyenv init -)" &&
            make setup &&
            PYTHONPATH=.. poetry run python run_cluster_distributed_benchmark.py
      restartPolicy: Never
  backoffLimit: 1
